
_target_: lightning.pytorch.loggers.MLFlowLogger
experiment_name: "meps-interpolation"
run_name: "run_${now:%Y%m%d_%H%M%S}"
tracking_uri: file:${_mlflow_dir}
tags:
  project: "diffusion_interpolation"
# requires mlflow >= 2.8.0; if older, just remove this flag
synchronous: false

