

_target_: data.MEPSNPYWindowDataModule
# Data
root: ${_data_dir}/merged_samples                              # link for tier1 data for high performance
sequences_csv: ${_data_dir}/sequences-2023-2024.csv        # grouped CSV with JSON columns
# Which members / leads to include (null = all present in CSV)
members: null                                      # e.g. [0,1,2]
leads: null                                        # e.g. [0,1,2,3,4,5,6]
require_internal_targets: true                     # need at least one internal lead
require_all_selected_members: true                 # skip windows missing any requested member
# Sample building
sample_mode: per_member                              # ensemble | per_member
file_channel_indices: [ 1, 2, 3]                    # pick C channels from each (4,H,W)
# Normalization
normalize: symrange                                    # none | zscore | symrange
stats_npz: ${_data_dir}/sequences-stats-2023-2024.npz
mean_key: mean
std_key: std
average_key: global_mean                        # if using symrange
global_min_key: global_min
global_max_key: global_max
norm_const: 0.95
# Loader
batch_size: 8  # multiplies by accumulate_grad_batches * devices * num_nodes to get effective batch size
num_workers: 2
pin_memory: true
shuffle_train: true
dtype: float32
mmap: true
# Split

split:
  type: ratio
  test: 0.1
  n_train_days_per_block: 25
  skip_after_train_days: 2
  n_val_days_per_block: 3
  skip_after_val_days: 2
  start_with: train